version: '3'
services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: chsm
      MONGO_INITDB_ROOT_PASSWORD: chsm
    ports:
      - "27017:27017"
    volumes:
      - /:/data/mongo
    networks:
      - server-network

  portainer:
    image: portainer/portainer
    volumes:
      - /:/data/portainer
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - server-network
    ports:
      - "9000:9000"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - server-network
    volumes:
      - /:/data/redis
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - /:/var/lib/postgresql/data
    networks:
      - server-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "16543:8082"
    depends_on:
      - postgres
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
